name: Run Test <Prod>
run-name: Test Prod

on:
  push:
    branches: [ main, dev ]
    tags: ["*"]

jobs:
  unit-e2e-test:
    name: Unit and E2E Test <Prod>
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: write Firebase service account key (from secrets to json)
        id: create-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "serviceAccountKey.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          dir: "./packages/backend/"

      - name: run test (unit & e2e)
        run: yarn test:ci-prod
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./packages/backend/serviceAccountKey.json
          FIREBASE_FIRESTORE_DATABASE_URL: ${{ secrets.FIREBASE_FIRESTORE_DATABASE_URL }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}