name: Run Test <Prod>
run-name: Test Prod

on:
    push:
        # branches: [main, dev]

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    deploy_and_test:
        runs-on: ubuntu-22.04
        environment: p0tion-ci-environment

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3

            # install deps
            - name: Install npm packages and write env
              run: |
                  yarn install --frozen-lockfile
                  echo "${{ secrets.ACTIONS_ENV_FILE }}" > ./packages/actions/.env
                  echo "${{ secrets.BACKEND_ENV_FILE }}" > ./packages/backend/.env

            # save serviceAccountKey in a JSON file
            - name: write Firebase service account key
              id: create-json
              uses: jsdaniell/create-json@v1.2.1
              with:
                  name: "serviceAccountKey.json"
                  json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
                  dir: "./packages/backend/"

            # build
            - name: build packages
              run: yarn build
              env:
                  NODE_OPTIONS: "--max_old_space_size=4096"

            # Workaround for SSL error. (resource: https://github.com/firebase/firebase-admin-node/issues/1712)
            - name: SSL Workaround
              run: sudo sed -i '54 s/^/#/' /usr/lib/ssl/openssl.cnf

            # deploy functions
            - name: deploy to firebase
              run: yarn firebase:deploy-functions
              working-directory: ./packages/backend/
              env:
                  GOOGLE_APPLICATION_CREDENTIALS: ./serviceAccountKey.json

            # run unit and e2e testsd
            - name: run test (unit & e2e)
              run: yarn test:ci-prod
              env:
                  GOOGLE_APPLICATION_CREDENTIALS: ./packages/backend/serviceAccountKey.json
